services:
  server:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: .
      target: final
    ports:
      - 8080:8080
    restart: always
    volumes:
      - error_logs:/app/log/
    depends_on:
      clickhouse:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123"   # HTTP интерфейс
      - "9000:9000"   # Native TCP интерфейс
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok.'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  migrate:
    build:
      dockerfile: ./docker/migrator/Dockerfile
      context: .
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations

volumes:
  error_logs:
  clickhouse_data:
  clickhouse_logs:
